export let GET_ERRORS = "GET_ERRORS";
export let SET_CURRENT_USER = "SET_CURRENT_USER";
export let GET_PROFILE = "GET_PROFILE";
export let PROFILE_LOADING = "PROFILE_LOADING";
export let PROFILE_NOT_FOUND = "PROFILE_NOT_FOUND";
export let CLEAR_CURRENT_PROFILE = "CLEAR_CURRENT_PROFILE";
export let GET_PROFILES = "GET_PROFILES";
